export const CATEGORY_NAME = {
  GIOI_THIEU: 'Giới thiệu',
  GIAO_VIEN: 'Giáo viên',
  LICH_KHAI_GIANG: 'Lịch khai giảng',
  KHOA_HOC: 'Khoá học IELTS',
  TAI_LIEU: 'Tài liệu IELTS',
  HOC_IELTS_ONLINE: 'Học IELTS online',
  HOC_IELTS_ONLINE_VOCABULARY: 'IELTS vocabulary',
  HOC_IELTS_ONLINE_GRAMMAR: 'IELTS Grammar',
  HOC_IELTS_ONLINE_READING: 'IELTS Reading',
  HOC_IELTS_ONLINE_LISTENING: 'IELTS Listening',
  HOC_IELTS_ONLINE_SPEAKING: 'IELTS Speaking',
  HOC_IELTS_ONLINE_WRITING: 'IELTS Writing',
  TIN_TUC: 'Tin Tức',
  SU_KIEN: 'Sự kiện',
  HOAT_DONG_NOI_BO: 'Hoạt động nội bộ',
};
