export enum EIconName {
  ICON_HAMBURGER = 'ICON_HAMBURGER',
  ICON_ARROW_DOWN = 'ICON_ARROW_DOWN',
  ICON_PHONE = 'ICON_PHONE',
  ICON_MAIL = 'ICON_MAIL',
  ICON_SEARCH = 'ICON_SEARCH',
  ICON_SOCIAL_INSTAGRAM = 'ICON_SOCIAL_INSTAGRAM',
  ICON_SOCIAL_TIKTOK = 'ICON_SOCIAL_TIKTOK',
  ICON_SOCIAL_YOUTUBE = 'ICON_SOCIAL_YOUTUBE',
  ICON_SOCIAL_FACEBOOK = 'ICON_SOCIAL_FACEBOOK',
  ICON_MAIL_LARGER = 'ICON_MAIL_LARGER',
}
